### ISSUE TITLE
Variant=Short in NOUNs and PROPNs

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Lithuanian-ALKSNIS#1]
There is a feature Variant=Short obligatory for all nouns. Was it a conversion error?
e.g. Case=Nom|Gender=Masc|Number=Sing|Variant=Short

**Comment by dan-zeman** [comment]
It may be a misinterpretation of a feature in the MULTEXT-EAST tagset. I did not have documentation of the Lithuanian version of the tagset. Maybe it should have been interpreted as reflexivity (with the value No, which would result in no UD feature).

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/UD_Lithuanian-ALKSNIS/commit/591c09e445c6621878e2050ea2808bab621c8b3e
