### ISSUE TITLE
Definite=Ind for numbers

### ISSUE THREAD

**Issue by fjagiell** [UniversalDependencies/UD_Lithuanian-ALKSNIS#4]
Numbers seem to be listed with the exact same features except that sometimes they are specified as Definite=Ind and other times this feature is unspecified. Is there a difference between the two?

For example:
Wordform "<tūkstančių>" has the following two lemmas.
tūkstantis" NUM Case=Gen Gender=Masc Number=Plur NumForm=Word NumType=Card
"tūkstantis" NUM Case=Gen Definite=Ind Gender=Masc Number=Plur NumForm=Word NumType=Card

**Comment by dan-zeman** [comment]
It is probably an annotation error. The definiteness feature seems to be relevant for the adjectival (ordinal) numerals but not for cardinals.

**Comment by dan-zeman** [comment]
It should be fixed in the dev branch now.

**Comment by ftyers** [comment]
Thanks @dan-zeman !
