### ISSUE TITLE
m. Category for years

### ISSUE THREAD

**Issue by fjagiell** [UniversalDependencies/UD_Lithuanian-ALKSNIS#5]
The abbreviation m., used after years is listed with both X and ADV as categories. Should it only be one of the two, as they appear to be functioning the same way?

Examples:
baznyciomis_V1-s18: 1990 m. The m. is categorized as ADV.
balandzio_V1-s3 1999 m. The m. is categorized as X.

**Comment by dan-zeman** [comment]
As it seems to be an abbreviation of _metus_ “year”, I suppose it should be `NOUN`?

This is a conversion error. The original tag is always `Ys`, which simply means “abbreviation” and would lead to `X` in UD. But in some cases it is attached as `advmod` and then the conversion software deduces that it is an adverb. In fact, it should not be `advmod` but `obl`.

**Comment by dan-zeman** [comment]
Fixed in 035a032.
